FROM mcr.microsoft.com/devcontainers/python:3.11

# Instalamos PostgreSQL
RUN apt-get update && \
    apt-get install -y postgresql postgresql-contrib && \
    apt-get clean

# Copiamos el script de arranque de PostgreSQL al contenedor
COPY .devcontainer/start-postgres.sh /usr/local/bin/start-postgres.sh

# Le damos permisos de ejecución
RUN chmod +x /usr/local/bin/start-postgres.sh
