FROM mcr.microsoft.com/devcontainers/python:3.11

RUN echo "vscode ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/vscode && chmod 0440 /etc/sudoers.d/vscode
RUN apt-get update && \
    apt-get install -y postgresql postgresql-contrib && \
    apt-get clean

# Copiamos el script de arranque (como están en la misma carpeta)
COPY start-postgres.sh /usr/local/bin/start-postgres.sh

# Damos permisos de ejecución
RUN chmod +x /usr/local/bin/start-postgres.sh
